### ISSUE TITLE
Bad feedback when up section is invalid

### ISSUE THREAD

**Issue by pior** [pior/dad#13]
```bash
$ dad up
Error: yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into []interface {}
```

```yaml
up:
  python: 2.7.13
  custom:
    command: pip install -e .
  custom:
    command: pip install ./[testing]

commands:
  test:
    run: nosetests
```

**Comment by pior** [comment]
```
$ dad up
Error: error parsing tasks: map[custom:map[command:pip install -e .]]
```

```yaml
up:
  - python: 2.7.13
  - custom:
      command: pip install -e .
  - custom:
      command: pip install ./[testing]

commands:
  test:
    run: nosetests
```
